### ISSUE TITLE
[Question] 1.20.1 When?

### ISSUE THREAD

**Issue by Fyoncle** [legosteenjaap/HorseInBoat#13]
Yeah thats it, 1.20.1 :(

**Comment by legosteenjaap** [comment]
You can use the 1.20 version. I marked them compatible on curseforge and modrinth.

**Comment by Fyoncle** [comment]
> You can use the 1.20 version. I marked them compatible on curseforge and modrinth.

❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️
