### ISSUE TITLE
[visual bug] Horse legs sticking out when inside a boat.

### ISSUE THREAD

**Issue by SehdCode** [legosteenjaap/HorseInBoat#2]
Horse legs sticking out when inside a boat.

**Comment by legosteenjaap** [comment]
![2022-02-06_14 12 51](https://user-images.githubusercontent.com/50271899/152682571-5dfd9024-102f-47e7-9a8f-e49ceb007eea.png)
fixed

**Comment by legosteenjaap** [comment]
will try to make the horse really sit

**Comment by legosteenjaap** [comment]
![2022-02-06_22 18 36](https://user-images.githubusercontent.com/50271899/152705194-11ae91b3-a3e5-4d25-aec8-1777259c04a8.png)
fixed
