### ISSUE TITLE
[visual bug] Baby horse's legs are improperly shifted while inside a boat/doesn't pose at all

### ISSUE THREAD

**Issue by MaranRoseGIT** [legosteenjaap/HorseInBoat#4]
**_Minecraft 1.18.2 Fabric_**
![1](https://user-images.githubusercontent.com/80443691/167681880-6bcff627-b134-4cbe-b7a4-94918c880f36.png)
![2](https://user-images.githubusercontent.com/80443691/167681881-b6d38b43-11e8-451d-8cca-57805a558117.png)
![3](https://user-images.githubusercontent.com/80443691/167681882-2d488db0-a9e6-437a-b52f-957a067384d4.png)

**Comment by legosteenjaap** [comment]
Fixed in version 1.1.2
