### ISSUE TITLE
[Forge 1.18.2] Crash on startup 

### ISSUE THREAD

**Issue by Zano1999** [legosteenjaap/HorseInBoat#5]
Forge version: 40.1.16
Mod version: 1.1.2

Crash log: https://pastebin.com/xvyJhT5T

**Comment by legosteenjaap** [comment]
Weird, i can't reproduce this issue. Can you reproduce this without any other mods installed?

**Comment by ProsperCraft** [comment]
Same problem with forge .25
horseinboat-forge-1.1.2.jar

https://gist.github.com/ProsperCraft/ffdaf1bdcf5309c906b7df63bfffb2e8

Problem resolved by removing HorseInBoat.

**Comment by legosteenjaap** [comment]
Could you send your mod list?
