### ISSUE TITLE
Crash on client loading

### ISSUE THREAD

**Issue by ghost** [legosteenjaap/HorseInBoat#7]
Hello, I was trying to load the mod, but I got this error: https://pastebin.com/raw/Qc9jaQS0

**Comment by legosteenjaap** [comment]
Can you send me your modlist, that would probally help me fix this bug faster.

**Comment by legosteenjaap** [comment]
Can you also try to run minecraft with no mods installed except horseinboat and slowly add more mods until it crashes?

**Comment by ghost** [comment]
I will send you my modlist soon.
I have two mods with changing boat behaviour - this is the first what comes into my mind. I check that.

**Comment by legosteenjaap** [comment]
That hopefully explains it

**Comment by ghost** [comment]
The two mods I meantioned before are...
Jumpy Boats: https://www.curseforge.com/minecraft/mc-mods/jumpy-boats
And BoatJump: https://modrinth.com/mod/boatjump
It still crashes when I remove them. I try now other mods who taking control on the horses, I will post my results.

**Comment by ghost** [comment]
I spotted the mod @legosteenjaap 😄
Dual Riders: https://www.curseforge.com/minecraft/mc-mods/dual-riders
The mod works fine between my other 253 files, just this mod causes the error.

**Comment by legosteenjaap** [comment]
Thanks for helping! I think that i have an idea why it crashes so hopefully i can fix it.

**Comment by legosteenjaap** [comment]
Weird Dual Riders can also crash on startup without horseinboat installed. I installed it together with a mod called biomemakeover and it also crashed. I will probally try to report it to Dual Riders, because their mod isn't opensource so it is quite hard for me to fix the issue.

**Comment by legosteenjaap** [comment]
Is it ok if i close this issue or should i wait?

**Comment by ghost** [comment]
Sounds good, here is the link for Flytres Discord: https://discord.flytre.net/
Thank you again, I hope he can fiddle it out:D

**Comment by legosteenjaap** [comment]
Yep
